sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
  - "npm install velocity-cli -g"
env:
  - TEST_COMMAND=meteor
script: 
- "velocity test-app --ci"